require('./db/conn')
const path = require('path')
const mongoose = require('mongoose')
const express = require('express')
const cors = require('cors')
const cookieParser = require('cookie-parser')
const app = express()
const signupRoute = require('./routes/signupRoute')
const loginRoute = require('./routes/loginRoute')
const appRoute = require('./routes/appRoute')
app.use(express.json({}))
app.use(cors())
app.use(cookieParser())
app.use(signupRoute)
app.use(loginRoute)
app.use(appRoute)
app.listen(process.env.PORT,()=>{
    console.log(`Listening at port ${process.env.PORT}`)
})
